export * from './account.service';
import { AccountService } from './account.service';
export * from './accountActions.service';
import { AccountActionsService } from './accountActions.service';
export * from './ageCategory.service';
import { AgeCategoryService } from './ageCategory.service';
export * from './availability.service';
import { AvailabilityService } from './availability.service';
export * from './block.service';
import { BlockService } from './block.service';
export * from './blockActions.service';
import { BlockActionsService } from './blockActions.service';
export * from './booking.service';
import { BookingService } from './booking.service';
export * from './bookingLogs.service';
import { BookingLogsService } from './bookingLogs.service';
export * from './cancellationPolicy.service';
import { CancellationPolicyService } from './cancellationPolicy.service';
export * from './capturePolicies.service';
import { CapturePoliciesService } from './capturePolicies.service';
export * from './cityTax.service';
import { CityTaxService } from './cityTax.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './corporateCodes.service';
import { CorporateCodesService } from './corporateCodes.service';
export * from './customSubAccounts.service';
import { CustomSubAccountsService } from './customSubAccounts.service';
export * from './featureSettings.service';
import { FeatureSettingsService } from './featureSettings.service';
export * from './financeLogs.service';
import { FinanceLogsService } from './financeLogs.service';
export * from './folio.service';
import { FolioService } from './folio.service';
export * from './folioActions.service';
import { FolioActionsService } from './folioActions.service';
export * from './folioPayments.service';
import { FolioPaymentsService } from './folioPayments.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './invoice.service';
import { InvoiceService } from './invoice.service';
export * from './invoiceAction.service';
import { InvoiceActionService } from './invoiceAction.service';
export * from './invoiceAddress.service';
import { InvoiceAddressService } from './invoiceAddress.service';
export * from './languages.service';
import { LanguagesService } from './languages.service';
export * from './maintenance.service';
import { MaintenanceService } from './maintenance.service';
export * from './noShowPolicy.service';
import { NoShowPolicyService } from './noShowPolicy.service';
export * from './offer.service';
import { OfferService } from './offer.service';
export * from './operations.service';
import { OperationsService } from './operations.service';
export * from './promoCodes.service';
import { PromoCodesService } from './promoCodes.service';
export * from './property.service';
import { PropertyService } from './property.service';
export * from './propertySettings.service';
import { PropertySettingsService } from './propertySettings.service';
export * from './rate.service';
import { RateService } from './rate.service';
export * from './ratePlan.service';
import { RatePlanService } from './ratePlan.service';
export * from './ratePlanCodes.service';
import { RatePlanCodesService } from './ratePlanCodes.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './reservation.service';
import { ReservationService } from './reservation.service';
export * from './reservationActions.service';
import { ReservationActionsService } from './reservationActions.service';
export * from './reservationAvailability.service';
import { ReservationAvailabilityService } from './reservationAvailability.service';
export * from './service.service';
import { ServiceService } from './service.service';
export * from './subLedger.service';
import { SubLedgerService } from './subLedger.service';
export * from './timeSliceDefinitions.service';
import { TimeSliceDefinitionsService } from './timeSliceDefinitions.service';
export * from './types.service';
import { TypesService } from './types.service';
export * from './unit.service';
import { UnitService } from './unit.service';
export * from './unitAttribute.service';
import { UnitAttributeService } from './unitAttribute.service';
export * from './unitGroup.service';
import { UnitGroupService } from './unitGroup.service';
export const APIS = [AccountService, AccountActionsService, AgeCategoryService, AvailabilityService, BlockService, BlockActionsService, BookingService, BookingLogsService, CancellationPolicyService, CapturePoliciesService, CityTaxService, CompanyService, CorporateCodesService, CustomSubAccountsService, FeatureSettingsService, FinanceLogsService, FolioService, FolioActionsService, FolioPaymentsService, GroupService, InvoiceService, InvoiceActionService, InvoiceAddressService, LanguagesService, MaintenanceService, NoShowPolicyService, OfferService, OperationsService, PromoCodesService, PropertyService, PropertySettingsService, RateService, RatePlanService, RatePlanCodesService, ReportsService, ReservationService, ReservationActionsService, ReservationAvailabilityService, ServiceService, SubLedgerService, TimeSliceDefinitionsService, TypesService, UnitService, UnitAttributeService, UnitGroupService];
