/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionReasonModelNotAllowedReservationTimeSliceActionReason } from './actionReasonModelNotAllowedReservationTimeSliceActionReason';


export interface ActionModelReservationTimeSliceActionNotAllowedReservationTimeSliceActionReason { 
    action: ActionModelReservationTimeSliceActionNotAllowedReservationTimeSliceActionReason.ActionEnum;
    isAllowed: boolean;
    reasons?: Array<ActionReasonModelNotAllowedReservationTimeSliceActionReason>;
}
export namespace ActionModelReservationTimeSliceActionNotAllowedReservationTimeSliceActionReason {
    export type ActionEnum = 'Amend';
    export const ActionEnum = {
        Amend: 'Amend' as ActionEnum
    };
}


