/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActionReasonModelNotAllowedTimeSliceDefinitionActionReason { 
    code: ActionReasonModelNotAllowedTimeSliceDefinitionActionReason.CodeEnum;
    message: string;
}
export namespace ActionReasonModelNotAllowedTimeSliceDefinitionActionReason {
    export type CodeEnum = 'ModifyCheckInCheckOutTimeNotAllowedForUsedTimeSliceDefinition' | 'DeleteIsNotAllowedForUsedTimeSliceDefinition';
    export const CodeEnum = {
        ModifyCheckInCheckOutTimeNotAllowedForUsedTimeSliceDefinition: 'ModifyCheckInCheckOutTimeNotAllowedForUsedTimeSliceDefinition' as CodeEnum,
        DeleteIsNotAllowedForUsedTimeSliceDefinition: 'DeleteIsNotAllowedForUsedTimeSliceDefinition' as CodeEnum
    };
}


