/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailableUnitItemStatusModel { 
    isOccupied: boolean;
    condition: AvailableUnitItemStatusModel.ConditionEnum;
    maintenanceType?: AvailableUnitItemStatusModel.MaintenanceTypeEnum;
}
export namespace AvailableUnitItemStatusModel {
    export type ConditionEnum = 'Clean' | 'CleanToBeInspected' | 'Dirty';
    export const ConditionEnum = {
        Clean: 'Clean' as ConditionEnum,
        CleanToBeInspected: 'CleanToBeInspected' as ConditionEnum,
        Dirty: 'Dirty' as ConditionEnum
    };
    export type MaintenanceTypeEnum = 'OutOfService' | 'OutOfOrder' | 'OutOfInventory';
    export const MaintenanceTypeEnum = {
        OutOfService: 'OutOfService' as MaintenanceTypeEnum,
        OutOfOrder: 'OutOfOrder' as MaintenanceTypeEnum,
        OutOfInventory: 'OutOfInventory' as MaintenanceTypeEnum
    };
}


