/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateUnitModel } from './createUnitModel';
import { CreateUnitAttributeModel } from './createUnitAttributeModel';


export interface BulkCreateUnitsModel { 
    /**
     * The id of the property where the units will be created - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    propertyId?: string;
    /**
     * The list of unit names - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    names?: Array<string>;
    /**
     * The description, used for all units - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    description?: { [key: string]: string; };
    /**
     * The id of the unit group used for all units - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    unitGroupId?: string;
    /**
     * Maximum number of persons for the units - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    maxPersons?: number;
    /**
     * Condition of the unit - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    condition?: BulkCreateUnitsModel.ConditionEnum;
    /**
     * Collection of user defined attributes of unit - <b>DEPRECATED: This field will be removed at 15.08.2021. Use `Units` for creating in bulk instead</b>
     */
    attributes?: Array<CreateUnitAttributeModel>;
    units?: Array<CreateUnitModel>;
}
export namespace BulkCreateUnitsModel {
    export type ConditionEnum = 'Clean' | 'CleanToBeInspected' | 'Dirty';
    export const ConditionEnum = {
        Clean: 'Clean' as ConditionEnum,
        CleanToBeInspected: 'CleanToBeInspected' as ConditionEnum,
        Dirty: 'Dirty' as ConditionEnum
    };
}


