/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CapturePolicyItemModel } from './capturePolicyItemModel';


export interface CapturePolicyListModel { 
    /**
     * List of capture policies
     */
    capturePolicies: Array<CapturePolicyItemModel>;
    /**
     * Total count of items
     */
    count: number;
}

