/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CityTaxSubcategoryAgeModel } from './cityTaxSubcategoryAgeModel';


export interface CityTaxSubcategoryModel { 
    /**
     * The name of the city tax subcategory
     */
    name: { [key: string]: string; };
    /**
     * Fixed value of the tax for this age category
     */
    value: number;
    age: CityTaxSubcategoryAgeModel;
}

