/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyRatePlanModel { 
    /**
     * Company ID that can use this rate plan
     */
    id: string;
    /**
     * The code of the company that can book this rate plan
     */
    code: string;
    /**
     * Company rate plan code, identifying the company + rate plan pair. Is used is offers.
     */
    corporateCode: string;
    /**
     * The name of the company that can book this rate plan
     */
    name: string;
}

