/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FolioDebitorModel } from './folioDebitorModel';


export interface CreateFolioModel { 
    /**
     * The ID of the reservation for which a guest folio should be created
     */
    reservationId?: string;
    /**
     * The ID of the company for which a folio should be created
     */
    companyId?: string;
    debitor: FolioDebitorModel;
    /**
     * The type of the folio to create. Default is the guest folio.  This field will become required 01.11.2019.
     */
    type?: CreateFolioModel.TypeEnum;
    /**
     * The ID of the property for which an external folio should be created.
     */
    propertyId?: string;
    /**
     * Optional code for external folios.  If present, the id of the folio will be propertyId-code (MUC-SOMETHING);  If no code is provided, the id of the folio will be propertyId-ext-number (MUC-EXT-282).
     */
    code?: string;
}
export namespace CreateFolioModel {
    export type TypeEnum = 'Guest' | 'External';
    export const TypeEnum = {
        Guest: 'Guest' as TypeEnum,
        External: 'External' as TypeEnum
    };
}


