/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAddressModel { 
    addressLine1: string;
    addressLine2?: string;
    postalCode: string;
    city: string;
    /**
     * The ISO 3166-2 code
     */
    regionCode?: string;
    /**
     * The country code, in ISO 3166-1 alpha-2 code
     */
    countryCode: string;
}

