/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonetaryValueModel } from './monetaryValueModel';


export interface CreateChargeModel { 
    /**
     * The service type, used by accounting to determine the correct revenue account
     */
    serviceType: CreateChargeModel.ServiceTypeEnum;
    /**
     * The VAT type, used by accounting to determine the correct vat amount and account
     */
    vatType: CreateChargeModel.VatTypeEnum;
    /**
     * ID of the custom sub-account to post the charge to, used by accounting to determine the correct revenue account
     */
    subAccountId?: string;
    /**
     * The name, article number, or other description of this charge
     */
    name: string;
    amount: MonetaryValueModel;
    /**
     * Receipt for this transaction
     */
    receipt?: string;
    /**
     * The count of services provided. Defaults to 1.  NOTE: this field will become required 07.05.2020.
     */
    quantity?: number;
    /**
     * The business date of the charge. Defaults to the current date.  In some cases you might want to post the charges to the previous business date, this is only possible until 6 AM of the current day.
     */
    businessDate?: string;
}
export namespace CreateChargeModel {
    export type ServiceTypeEnum = 'Other' | 'Accommodation' | 'FoodAndBeverages' | 'CityTax';
    export const ServiceTypeEnum = {
        Other: 'Other' as ServiceTypeEnum,
        Accommodation: 'Accommodation' as ServiceTypeEnum,
        FoodAndBeverages: 'FoodAndBeverages' as ServiceTypeEnum,
        CityTax: 'CityTax' as ServiceTypeEnum
    };
    export type VatTypeEnum = 'Null' | 'VeryReduced' | 'Reduced' | 'Normal' | 'Without' | 'Special' | 'ReducedCovid19' | 'NormalCovid19';
    export const VatTypeEnum = {
        Null: 'Null' as VatTypeEnum,
        VeryReduced: 'VeryReduced' as VatTypeEnum,
        Reduced: 'Reduced' as VatTypeEnum,
        Normal: 'Normal' as VatTypeEnum,
        Without: 'Without' as VatTypeEnum,
        Special: 'Special' as VatTypeEnum,
        ReducedCovid19: 'ReducedCovid19' as VatTypeEnum,
        NormalCovid19: 'NormalCovid19' as VatTypeEnum
    };
}


