/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonetaryValueModel } from './monetaryValueModel';


export interface CreateFolioRefundRequest { 
    /**
     * The payment method the refund will be accounted to
     */
    method: CreateFolioRefundRequest.MethodEnum;
    amount: MonetaryValueModel;
    /**
     * The receipt for the refund
     */
    receipt?: string;
    /**
     * The business date of the refund. Defaults to the current date.  In some cases you might want to post the refunds to the previous business date, this is only possible until 6 AM of the current day.
     */
    businessDate?: string;
}
export namespace CreateFolioRefundRequest {
    export type MethodEnum = 'Cash' | 'BankTransfer' | 'CreditCard' | 'Amex' | 'VisaCredit' | 'VisaDebit' | 'MasterCard' | 'MasterCardDebit' | 'Maestro' | 'GiroCard' | 'DiscoverCard' | 'Diners' | 'Jcb' | 'BookingCom' | 'VPay' | 'PayPal' | 'Postcard' | 'Reka' | 'Twint' | 'Lunchcheck' | 'Voucher' | 'ChinaUnionPay' | 'Other' | 'Cheque' | 'Airbnb' | 'HolidayCheck';
    export const MethodEnum = {
        Cash: 'Cash' as MethodEnum,
        BankTransfer: 'BankTransfer' as MethodEnum,
        CreditCard: 'CreditCard' as MethodEnum,
        Amex: 'Amex' as MethodEnum,
        VisaCredit: 'VisaCredit' as MethodEnum,
        VisaDebit: 'VisaDebit' as MethodEnum,
        MasterCard: 'MasterCard' as MethodEnum,
        MasterCardDebit: 'MasterCardDebit' as MethodEnum,
        Maestro: 'Maestro' as MethodEnum,
        GiroCard: 'GiroCard' as MethodEnum,
        DiscoverCard: 'DiscoverCard' as MethodEnum,
        Diners: 'Diners' as MethodEnum,
        Jcb: 'Jcb' as MethodEnum,
        BookingCom: 'BookingCom' as MethodEnum,
        VPay: 'VPay' as MethodEnum,
        PayPal: 'PayPal' as MethodEnum,
        Postcard: 'Postcard' as MethodEnum,
        Reka: 'Reka' as MethodEnum,
        Twint: 'Twint' as MethodEnum,
        Lunchcheck: 'Lunchcheck' as MethodEnum,
        Voucher: 'Voucher' as MethodEnum,
        ChinaUnionPay: 'ChinaUnionPay' as MethodEnum,
        Other: 'Other' as MethodEnum,
        Cheque: 'Cheque' as MethodEnum,
        Airbnb: 'Airbnb' as MethodEnum,
        HolidayCheck: 'HolidayCheck' as MethodEnum
    };
}


