/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonetaryValueModel } from './monetaryValueModel';


export interface CreatePaymentRefundRequest { 
    amount: MonetaryValueModel;
    /**
     * The business date of the refund. Defaults to the current date.  In some cases you might want to post the refunds to the previous business date, this is only possible until 6 AM of the current day.
     */
    businessDate?: string;
}

