/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateAddressModel } from './createAddressModel';
import { BankAccountModel } from './bankAccountModel';


export interface CreatePropertyModel { 
    /**
     * The code for the property that can be shown in reports and table views
     */
    code: string;
    /**
     * The name for the property
     */
    name: { [key: string]: string; };
    /**
     * The legal name of the company running the property.
     */
    companyName: string;
    /**
     * The managing director(s) of the company, as they should appear on invoices
     */
    managingDirectors?: string;
    /**
     * The entry in the Commercial Reigster of the company running the property, as it should appear on invoices
     */
    commercialRegisterEntry: string;
    /**
     * The Tax-ID of the company running the property, as it should appear on invoices
     */
    taxId: string;
    /**
     * The description for the property
     */
    description?: { [key: string]: string; };
    location: CreateAddressModel;
    bankAccount?: BankAccountModel;
    /**
     * The payment terms used for all rate plans
     */
    paymentTerms: { [key: string]: string; };
    /**
     * The time zone name of the property from the IANA Time Zone Database.  (see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
     */
    timeZone: string;
    /**
     * The default check-in time<br />A time (without fractional second part) as defined in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    defaultCheckInTime: string;
    /**
     * The default check-out time<br />A time (without fractional second part) as defined in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    defaultCheckOutTime: string;
    /**
     * The currency a property works with.
     */
    currencyCode: string;
}

