/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeatureSettingsModel { 
    /**
     * Are custom sub-accounts for revenue enabled.
     */
    areCustomRevenueSubAccountsEnabled: boolean;
    /**
     * Whether marking an AR invoice as paid leads to accounting or not.
     */
    performAccountingWhenInvoiceIsMarkedAsPaid: boolean;
    /**
     * Whether to display the main guest\'s name for each charge on the invoice if the invoice contains charges from several reservations.
     */
    showRecipientForEachLineItemOnTheInvoice: boolean;
    /**
     * If the amount for the invoice is lower than this value, allow creating invoices with the name only.
     */
    maxAmountForMinimalInvoices?: number;
    /**
     * Pattern to generate the invoice number.  Consists of three parts: custom prefix (optional),  date template (optional),  and number template (required).  use \'0\' for numbers;  \'d\' or \'dd\' for days;  \'M\' or \'MM\' for months;  \'yy\' or \'yyyy\' for years.  To set a custom prefix, enclose it in quotation marks (\").  Allowed symbols in the prefix: digits, uppercase letters, .,_,-.  Example: pattern \"MUC-\"yyyy0000 will produce invoice numbers like MUC-20190001.
     */
    invoiceNumberPattern: string;
    /**
     * Pattern to generate the advance invoice number.  Consists of three parts: custom prefix (optional),  date template (optional),  and number template (required).  use \'0\' for numbers;  \'d\' or \'dd\' for days;  \'M\' or \'MM\' for months;  \'yy\' or \'yyyy\' for years.  To set a custom prefix, enclose it in quotation marks (\").  Allowed symbols in the prefix: digits, uppercase letters, .,_,-.  Example: pattern \"MUC-\"yyyy0000 will produce invoice numbers like MUC-20190001.
     */
    advanceInvoiceNumberPattern: string;
}

