/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonetaryValueModel } from './monetaryValueModel';
import { PercentValueModel } from './percentValueModel';


export interface FeeDetailsModel { 
    /**
     * VAT that applies for the fee
     */
    vatType: FeeDetailsModel.VatTypeEnum;
    fixedValue?: MonetaryValueModel;
    percentValue?: PercentValueModel;
}
export namespace FeeDetailsModel {
    export type VatTypeEnum = 'Null' | 'VeryReduced' | 'Reduced' | 'Normal' | 'Without' | 'Special' | 'ReducedCovid19' | 'NormalCovid19';
    export const VatTypeEnum = {
        Null: 'Null' as VatTypeEnum,
        VeryReduced: 'VeryReduced' as VatTypeEnum,
        Reduced: 'Reduced' as VatTypeEnum,
        Normal: 'Normal' as VatTypeEnum,
        Without: 'Without' as VatTypeEnum,
        Special: 'Special' as VatTypeEnum,
        ReducedCovid19: 'ReducedCovid19' as VatTypeEnum,
        NormalCovid19: 'NormalCovid19' as VatTypeEnum
    };
}


