/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedPropertyModel } from './embeddedPropertyModel';
import { MonetaryValueModel } from './monetaryValueModel';
import { EmbeddedUnitGroupModel } from './embeddedUnitGroupModel';
import { EmbeddedRatePlanModel } from './embeddedRatePlanModel';


export interface GroupBlockModel { 
    /**
     * Block id
     */
    id: string;
    /**
     * Status of the block
     */
    status: GroupBlockModel.StatusEnum;
    property: EmbeddedPropertyModel;
    ratePlan: EmbeddedRatePlanModel;
    unitGroup: EmbeddedUnitGroupModel;
    grossDailyRate: MonetaryValueModel;
    /**
     * Start date and time from which the inventory will be blocked<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    from: string;
    /**
     * End date and time until which the inventory will be blocked<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    to: string;
    /**
     * Number of units blocked
     */
    blockedUnits: number;
    /**
     * Number of reservations already picked from this block
     */
    pickedReservations: number;
    /**
     * Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    created: string;
    /**
     * Date of last modification<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    modified: string;
}
export namespace GroupBlockModel {
    export type StatusEnum = 'Tentative' | 'Definite' | 'Canceled';
    export const StatusEnum = {
        Tentative: 'Tentative' as StatusEnum,
        Definite: 'Definite' as StatusEnum,
        Canceled: 'Canceled' as StatusEnum
    };
}


