/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentAccountModel } from './paymentAccountModel';
import { BookerModel } from './bookerModel';
import { GroupBlockModel } from './groupBlockModel';
import { ActionModelGroupActionNotAllowedGroupActionReason } from './actionModelGroupActionNotAllowedGroupActionReason';


export interface GroupModel { 
    /**
     * Group id
     */
    id: string;
    /**
     * Name of the group
     */
    name: string;
    /**
     * Start date and time of the earliest block for this group<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    from?: string;
    /**
     * End date and time of the latest block for this group<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    to?: string;
    booker?: BookerModel;
    /**
     * Additional information and comments
     */
    comment?: string;
    /**
     * Additional information and comment by the booker
     */
    bookerComment?: string;
    paymentAccount?: PaymentAccountModel;
    /**
     * Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    created: string;
    /**
     * Date of last modification<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO8601:2004</a>
     */
    modified: string;
    /**
     * Blocks within this group
     */
    blocks?: Array<GroupBlockModel>;
    /**
     * The list of actions for this group
     */
    actions?: Array<ActionModelGroupActionNotAllowedGroupActionReason>;
    /**
     * The list of property ids this group belongs to
     */
    propertyIds: Array<string>;
}

