/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoveChargesRequest { 
    /**
     * ID of the target folio
     */
    targetFolioId: string;
    /**
     * Description of why the move is performed
     */
    reason: string;
    /**
     * The IDs of the charges that should be moved
     */
    chargeIds?: Array<string>;
    /**
     * The IDs of the allowances that should be moved.  Only moving global allowances is supported
     */
    allowanceIds?: Array<string>;
    /**
     * The IDs of the transitory charges that should be moved
     */
    transitoryChargeIds?: Array<string>;
}

