/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonetaryValueModel } from './monetaryValueModel';
import { OfferCityTaxItemModel } from './offerCityTaxItemModel';


export interface OfferCityTaxModel { 
    /**
     * The id of the city tax
     */
    id: string;
    /**
     * The code of the city tax
     */
    code: string;
    /**
     * The name for the city tax
     */
    name: string;
    totalGrossAmount: MonetaryValueModel;
    /**
     * Split per day for the city tax
     */
    dates: Array<OfferCityTaxItemModel>;
}

