/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferValidationMessageModel { 
    /**
     * The message Code
     */
    code: OfferValidationMessageModel.CodeEnum;
    /**
     * The message description
     */
    message: string;
}
export namespace OfferValidationMessageModel {
    export type CodeEnum = 'UnitGroupFullyBooked' | 'UnitGroupCapacityExceeded' | 'RatePlanRestrictionsViolated' | 'RatePlanSurchargesNotSet' | 'RateRestrictionsViolated' | 'RatePlanChannelNotSet' | 'RatesNotSet' | 'BlockFullyBooked' | 'IncludedServicesAmountExceededRateAmount' | 'ServiceFullyBooked';
    export const CodeEnum = {
        UnitGroupFullyBooked: 'UnitGroupFullyBooked' as CodeEnum,
        UnitGroupCapacityExceeded: 'UnitGroupCapacityExceeded' as CodeEnum,
        RatePlanRestrictionsViolated: 'RatePlanRestrictionsViolated' as CodeEnum,
        RatePlanSurchargesNotSet: 'RatePlanSurchargesNotSet' as CodeEnum,
        RateRestrictionsViolated: 'RateRestrictionsViolated' as CodeEnum,
        RatePlanChannelNotSet: 'RatePlanChannelNotSet' as CodeEnum,
        RatesNotSet: 'RatesNotSet' as CodeEnum,
        BlockFullyBooked: 'BlockFullyBooked' as CodeEnum,
        IncludedServicesAmountExceededRateAmount: 'IncludedServicesAmountExceededRateAmount' as CodeEnum,
        ServiceFullyBooked: 'ServiceFullyBooked' as CodeEnum
    };
}


