/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PercentValueModel { 
    /**
     * Percent to take from the base. Must be between 0 and 100.
     */
    percent: number;
    /**
     * If set, limits the calculation base to the specified number of time slices, starting from the beginning.<br />  If not set, the entire stay will be used as a base.
     */
    limit?: number;
    /**
     * Services included in the calculation base. If none are set, only charges for the unit will be used.<br />  The services are only included, if they are part of the rate plan. Extra services are ignored.
     */
    includeServiceIds?: Array<string>;
}

