/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedServiceModel } from './embeddedServiceModel';
import { AmountModel } from './amountModel';


export interface ReservationServiceModel { 
    service: EmbeddedServiceModel;
    /**
     * The date this service is delivered
     */
    serviceDate: string;
    /**
     * The count of booked services
     */
    count: number;
    amount: AmountModel;
    /**
     * Whether this service is already booked as extra
     */
    bookedAsExtra: boolean;
}

