/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockServicesModel } from './blockServicesModel';
import { EmbeddedServiceModel } from './embeddedServiceModel';


export interface ServiceAvailabilityItemModel { 
    service: EmbeddedServiceModel;
    /**
     * The total number of services available.
     */
    quantity: number;
    /**
     * The number of sold services including included services picked up from blocks
     */
    soldCount: number;
    /**
     * The number of services still available. This is the total quantity excluding the already sold services.
     */
    availableCount: number;
    /**
     * The date this service is delivered
     */
    serviceDate: string;
    block: BlockServicesModel;
}

