/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AmountModel } from './amountModel';


export interface ServiceDateItemModel { 
    /**
     * The date this service is delivered
     */
    serviceDate: string;
    /**
     * The count of booked services
     */
    count: number;
    amount: AmountModel;
    /**
     * Rate plans can have additional services. When booking an offer for such rate plans, those services are automatically booked.  They are marked as mandatory and they cannot be removed.
     */
    isMandatory: boolean;
}

