/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSliceDefinitionModel } from './timeSliceDefinitionModel';


export interface TimeSliceDefinitionListModel { 
    timeSliceDefinitions: Array<TimeSliceDefinitionModel>;
    /**
     * Total count of items
     */
    count: number;
}

