/**
 * apaleo Inventory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnitAttributeDefinitionModel { 
    /**
     * The id of the unit attribute
     */
    id: string;
    /**
     * The name of the unit attribute
     */
    name: string;
    /**
     * The description of the unit attribute
     */
    description?: string;
}

