/**
 * Integration API
 * The Integration API allows apps to ...
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReplaceUiIntegrationModel { 
    /**
     * Label to be displayed as the name of your integration.  For example, this is the text that is displayed on your user\'s apps list.
     */
    label: string;
    /**
     * Different translations for the integration label.  You can provide as many translations as you want.  You should only provide the iso code of the language for example \'en\' for english and \'de\' for German. No need for the country.  If there is not a translation for a specific language, we will display the value of the Label as default.
     */
    labelTranslations?: { [key: string]: string; };
    iconSource?: string;
    sourceUrl: string;
    /**
     * Public source type means, that the browser can see the URL directly. This is true for instance, if you have Hybrid OAuth flow active.                Private source type means, that the server will request from that source URL a public URL, which is pre-authenticated and forward that to the client.
     */
    sourceType: ReplaceUiIntegrationModel.SourceTypeEnum;
    /**
     * List of Ids for the properties for which the integration is configured  If the list is empty then the integration is configured for all properties  Remark: Only applicable to non account level integrations
     */
    propertyIds?: Array<string>;
    /**
     * List of Roles for which the integration is configured to be used  If the list is empty then the integration is configured for all roles
     */
    roles?: Array<string>;
}
export namespace ReplaceUiIntegrationModel {
    export type SourceTypeEnum = 'Private' | 'Public';
    export const SourceTypeEnum = {
        Private: 'Private' as SourceTypeEnum,
        Public: 'Public' as SourceTypeEnum
    };
}


