/**
 * Integration API
 * The Integration API allows apps to ...
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UiIntegrationItemModel { 
    id: string;
    code: string;
    label: string;
    labelTranslations?: { [key: string]: string; };
    iconSource?: string;
    sourceUrl: string;
    propertyIds?: Array<string>;
    roles?: Array<string>;
    /**
     * Public source type means, that the browser can see the URL directly. This is true for instance, if you have Hybrid OAuth flow active.                Private source type means, that the server will request from that source URL a public URL, which is pre-authenticated and forward that to the client.
     */
    sourceType: UiIntegrationItemModel.SourceTypeEnum;
    target: UiIntegrationItemModel.TargetEnum;
}
export namespace UiIntegrationItemModel {
    export type SourceTypeEnum = 'Private' | 'Public';
    export const SourceTypeEnum = {
        Private: 'Private' as SourceTypeEnum,
        Public: 'Public' as SourceTypeEnum
    };
    export type TargetEnum = 'DashboardPropertyContext' | 'DashboardAccountContext' | 'ReservationDetailsTab' | 'PropertyMenuReports' | 'PropertyMenuApps' | 'AccountMenuApps' | 'CompanyDetailsTab';
    export const TargetEnum = {
        DashboardPropertyContext: 'DashboardPropertyContext' as TargetEnum,
        DashboardAccountContext: 'DashboardAccountContext' as TargetEnum,
        ReservationDetailsTab: 'ReservationDetailsTab' as TargetEnum,
        PropertyMenuReports: 'PropertyMenuReports' as TargetEnum,
        PropertyMenuApps: 'PropertyMenuApps' as TargetEnum,
        AccountMenuApps: 'AccountMenuApps' as TargetEnum,
        CompanyDetailsTab: 'CompanyDetailsTab' as TargetEnum
    };
}


